import { NextRequest, NextResponse } from "next/server";
import { generateSmartPath, hasAIKey, getAIProviderInfo } from "../../../lib/services/ai-router";
import { generatePath as generateRuleBasedPath } from "../../../lib/content/path-generator";

type Lang = "en" | "zh";

function parseLang(raw: unknown): Lang {
  if (raw === "zh" || raw === "en") return raw;
  return "en";
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { goal, useAI = false, lang = "en" } = body;

    if (!goal || typeof goal !== "string" || goal.trim().length === 0) {
      return NextResponse.json(
        { error: "Please enter your learning goal" },
        { status: 400 }
      );
    }

    const cleanGoal = goal.trim();
    const parsedLang = parseLang(lang);

    // AI 增强模式
    if (useAI && hasAIKey()) {
      const { path, provider } = await generateSmartPath(cleanGoal, parsedLang);

      if (path) {
        return NextResponse.json({
          ok: true,
          data: path,
          aiUsed: true,
          aiAvailable: true,
          aiProvider: provider,
          mode: "ai-enhanced",
          provider: provider,
          message: provider === "SiliconFlow"
            ? "Generated by AI (SiliconFlow)"
            : "Generated by AI (Groq)",
        });
      }

      // AI 生成失败，降级到规则匹配
      console.warn("AI generation failed, falling back to rule-based");
    }

    // 规则匹配模式（默认）
    const rulePath = generateRuleBasedPath(cleanGoal, parsedLang);

    return NextResponse.json({
      ok: true,
      data: rulePath,
      aiUsed: false,
      aiAvailable: hasAIKey(),
      aiProvider: getAIProviderInfo().providers[0] || null,
      mode: "rule-based",
      provider: null,
      message: "Generated by rule-based matching",
    });
  } catch (error) {
    console.error("Path generation error:", error);
    return NextResponse.json(
      { ok: false, error: "Failed to generate learning path. Please try again." },
      { status: 500 }
    );
  }
}

export async function GET() {
  const info = getAIProviderInfo();
  return NextResponse.json({
    ok: true,
    aiAvailable: info.available,
    aiProvider: info.providers[0] || null,
    providers: info.providers,
    message: info.available
      ? `AI providers available: ${info.providers.join(", ")}`
      : "No AI providers configured. Using rule-based matching.",
  });
}
